import { OnInit, TemplateRef } from '@angular/core';
import { NzFormatEmitEvent } from 'ng-zorro-antd';
export declare class TreeTransferComponent implements OnInit {
    titles: Array<string | TemplateRef<void>>;
    source: Array<any>;
    target: Array<string | number>;
    showSearch: boolean;
    footer: string | TemplateRef<void>;
    treeSearchValue: string;
    listSearchValue: string;
    listData: Array<any>;
    listCheckedKeys: Array<any>;
    treeCheckedKeys: Array<any>;
    treeExpandedKeys: Array<any>;
    treeExpandAll: boolean;
    leafKeys: Array<any>;
    allKeys: Array<any>;
    tree: any;
    constructor();
    ngOnInit(): void;
    initData(source: any): void;
    leftToRight(): void;
    rightToLeft(): void;
    treeOnCheck(event: NzFormatEmitEvent): void;
    treeOnCheckAll(e: boolean): void;
    listOnCheck(e: boolean, checkedKeys: any[]): void;
    listOnCheckAll(e: boolean): void;
    getTreeCheckedKeys(source: any): void;
    readonly getLeftDisabled: boolean;
    showListSearchValue(item: any): boolean;
    listSearch(e: any): void;
    treeSearch(e: any): void;
}
